spring:
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: 203.195.235.181:8848
    gateway:
      routes:
        - id: oauth
          uri: lb://amadeus-module2
          predicates:
            - Path=/module2/oauth/**
          filters:
            - My=My
        - id: amadeus-module2
          uri: lb://amadeus-module2
          predicates:
            - Path=/module2/**
        - id: amadeus-module1
          uri: lb://amadeus-module1
          predicates:
            - Path=/module1/**
        - id: baidu
          uri: http://www.baidu.com/
          predicates:
            - Path=/baidu/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-headers: "*"
            allow-credentials: true
            allowed-methods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTION
server:
port: 9004
mysql: 3306