spring:
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: 203.195.235.181:8848
    gateway:
      routes:
        - id: amadeus-module2
          uri: lb://amadeus-module2
          predicates:
            - Path=/module2/**
          filters:
            - Post=Post
            #自定义过滤器的名字为，GatewayFilterFactory前面的字符，比如 TokenGatewayFilterFactory，那么过滤器名字是 Token
        - id: amadeus-module1
          uri: lb://amadeus-module1
          predicates:
            - Path=/module1/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-headers: "*"
            allow-credentials: true
            allowed-methods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTION
server:
  port: 9004
mysql: 3306