spring:
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: 203.195.235.181:8848
    loadbalancer:
      ribbon:
        enabled: false
feign:
  sentinel:
    enabled: true
server:
  port: 8009
  servlet:
    context-path: /module2
mysql: 3306